name: Test Compile SuhabFiboTrader

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile SuhabFiboTrader_v5674.mq5
        shell: cmd
        run: |
          echo === Start compile ===
          "C:\Program Files\MetaTrader 5\metaeditor64.exe" /compile:"MQL5/Experts/Aegis/SuhabFiboTrade/SuhabFiboTrader_v5674.mq5" /log
          echo === Compile finished ===
